import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import Slider1 from '@/Component/ui/Slider1'
// import Cards from '@/Component/ui/Cards'
import Helicopter from '@/Component/ui/Helicopter'
import Yatches from '@/Component/ui/Yatches'
import Limousine from '@/Component/ui/Limousine'

const inter = Inter({ subsets: ['latin'] })
import CarRental from '@/Component/ui/CarRental'
import Menu from '@/Component/ui/Menu'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className='pt-2'>
          {/* <Menu/> */}
         <Yatches/>
         {/* <Helicopter/> */}
{/* <Limousine/> */}
{/* <CarRental/> */}
        </div>

      
      </main>
    </>
  );
}
